language: go

go:
  - 1.6
  - 1.7

python:
  - 3.5

env:
  - GOPATH=.

install:
  - go get golang.org/x/text
  - go get github.com/NYTimes/gziphandler

script:
  - go test github.com/rressi/smartsearch
